### PR TITLE
Setting to include passed tests in report | Use testsuite filename if testcase misses it

### LINKED ISSUE #42: Listing succeeded tests
Right now, seems that this action is listing tests with errors, however, as a build user, I want to be able to review which tests were effectively analyzed so that it would be great if tests that ended with success will be also printed but with green indicator ;) It would be nice to have such an input parameter that will control that. Still, the way in which the action is working actually could remain as default.

I've got only:

image

### LINKED ISSUE #401: Check <testsuite> for `file` attribute
The popular "mocha-junit-report" project attaches the `file` attribute to the `<testsuite>` tag, because Circle CI looks for it there. Test suites are not split over files, so it's waste of bytes to repeat the `file` attribute for every `<testcase>` within it.

https://github.com/michaelleeallen/mocha-junit-reporter/blob/master/index.js#L292

If there is `file` attribute on the current `<testcase>` use that, then next try the `file` attribute of the parent `<testsuite>`. Finally, fallback to trying to parse `classname` into a file. 

Here's the PR where `mocha-junit-reporter` proposed adding it five years ago:
https://github.com/michaelleeallen/mocha-junit-reporter/pull/41

### PR DESCRIPTION
**Pull request by mikepenz**
- add new setting allowing to include passed tests as `notice`
  - FIX https://github.com/mikepenz/action-junit-report/issues/42
- use testsuite file name in case testcase does not specify one
  - FIX https://github.com/mikepenz/action-junit-report/issues/401

### CODE REVIEW

**Comment by markstos** [comment]
Thanks, I'll test this!

**Comment by markstos** [comment]
I think there's one more piece that's needed. In the logs, I can see the XML has been processed, but then I don't see any annotations:

```
 /__w/proj/proj/test/config.js:1 | TESTING mocha-junit-reporter with Github Actions.
```

I believe the issue is that the absolute path needs to be stripped out so only the relative-to-repo-root path remains.

I expect it's normal for the "working directory" to be the repo root. So stripping the absolute path to current working directory should do the trick.

**Comment by mikepenz** [comment]
@markstos added the related change, if you could please re-run it :)

**Comment by markstos** [comment]
Thanks for the update. I know see the file path has been truncated from an absolute path to `/test/config.js`, but I still don't see the annotation. Should it be `test/config.js` instead with the leading "/" also stripped?

**Comment by mikepenz** [comment]
@markstos thank you, added the stripping of the last `/` too

**Comment by markstos** [comment]
It worked! The one area for improvement is the formatting of the annotation:

image

Notice how it repeats the absolute path name in red. I'm not sure if that can be changed, but that path doesn't need to be there at all. If it does need to stay, perhaps it can also be relative and there should be a space after the file name and before the test caes name. 

I found the line of code to consider changing, here:

https://github.com/mikepenz/action-junit-report/blob/3f8106d00b1ed055f3aba3801934d3ffe8b09c49/src/testParser.ts#L233

I don't see why `pos.title` is needed there. Since this is annotation on a file, I don't see why the file name needs to be repeated in the title.

**Comment by markstos** [comment]
Here's a commit that removes the file name from the the title. But from looking at the code and the test suite, it was quite intentionally there, so I presume it makes sense with other kind of Junit output:

https://github.com/RideAmigosCorp/action-junit-report/commit/16afe4fd45dece0c3cd116437b3faacb64b99a1a

That formatting question is a separate issue. The issue here with processing a "file" attribute appears correct and complete and the formatting issue can be addressed separately. An option could be used to include the file name in the title or not.

**Comment by mikepenz** [comment]
@markstos thank you for the feedback.

I am having an idea for an option which would make that much more flexible. Will see tomorrow if I'll find time to implement it prior to doing the next release.

**Pull request merged**
