### PR TITLE
Provide an example of using `workflow_run`

### PR DESCRIPTION
**Pull request by CAD97**

### CODE REVIEW

**Comment by mikepenz** [comment]
Thank you very much @CAD97 - Did rephrase it a little bit and added a collapsing code around. Also replaced the 3rd party action with the official download action

**Comment by CAD97** [comment]
Unfortunately the standard download action only works within a single workflow, and you need to use the rest API (or octokit) to access artifacts cross workflow

**Comment by mikepenz** [comment]
@CAD97 thank you. Guess I'll revert that part then. Usually I try to be as low on 3rd party actions as possible

**Comment by CAD97** [comment]
The alternative would be to use the `gh` cli or `actions/github-script` and write it out longform. It's not that difficult (the action used here is just a single file and mostly input handling at that) so it wouldn't complicate the example too much if you'd prefer to avoid the 3rd party action by including bespoke code.

I personally don't mind much either way, so long as the example actually works. I added it here because I spent a day trying to get the correct information out of the workflow_run payload and hope to avoid having to do so again. (Having the same "workflowish" data shape for both the running and the source workflow made that not super easy, especially combined with the typo=>empty semantics of workflow expressions.)

**Comment by CAD97** [comment]
I filed upstream feature requests to allow doing this using `actions/download-artifact` directly:

- https://github.com/actions/download-artifact/issues/172
- https://github.com/actions/toolkit/issues/1141

**Pull request merged**
