### PR TITLE
Improve Permissions-Related Example

### PR DESCRIPTION
**Pull request by amrwc**
## Summary

This change list adds an example of a workflow with a fine-grained `checks` permission, without the necessity for an extra workflow. It also uses the simpler [actions/download-artifact@v3](https://github.com/actions/download-artifact) action, and does not require accessing `github.event`.

## Context

I failed to make the 2 workflows solution work. For some reason, the dependant workflow never triggered, and did not appear in the Actions tab.

Came up with this approach, and I think it’s worth sharing.

### CODE REVIEW

**Comment by mikepenz** [comment]
Thank you very much for the PR. Really appreciate you sharing this here. 

However after looking into it, it's more focused on general GitHub actions, and is not specific to this action.

**Comment by amrwc** [comment]
> However after looking into it, it's more focused on general GitHub actions, and is not specific to this action.

What I meant by in this part:

> For some reason, the dependant workflow never triggered, and did not appear in the Actions tab.

is that the example from the readme didn’t work whatsoever, hence the attempts, and the solution.

**Comment by mikepenz** [comment]
Can you please clarify which example didn't work whatsoever?

We use a similar setup in multiple places and this works. 

Or are you referencing to this block:

```
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Download Test Report
        uses: dawidd6/action-download-artifact@v2
        with:
          name: junit-test-results
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        with:
          commit: ${{github.event.workflow_run.head_sha}}
          report_paths: '**/build/test-results/test/TEST-*.xml'
```

?

**Comment by amrwc** [comment]
Don’t remember the exact details, but I recall having issues with downloading the artifacts. If you’re interested, I could attempt to build a minimal reproducible example at some point by following the commit history.
image

**Comment by mikepenz** [comment]
Really appreciated. If it is more general on permissions of the CI or similar, I would suggest it being out of scope for this action. As this action does not include logic to download artifacts or more. 

The action will solely retrieve files located on the file system in the configured path. 

Thank you so much again!

**Pull request closed without merging**
