### PR TITLE
Summary parameter

### PR DESCRIPTION
**Pull request by oseasmoran73**
Hello!

Hope all is well! I am putting a PR for the following feature request.

Feature: The ability to pass `summary` and have it displayed via octokit in the report. This is a feature that is needed on my team and I believe it will also address issue to some extent [#42](https://github.com/mikepenz/action-junit-report/issues/42).

Regarding #42: While I am not certain how it would scale if this repo were to handle it, but rather have it be defaulted to the user/consumer. The way I am approaching it: by having `summary` parameter expose, I am passing in a string with all the information necessary (success, failed, codecoverage, etc.). Since Github Action allows markdown format, I have formatted `summary` (handled again by the user/consumer) and it will display nice (see updated testing in `build.yml`.

### CODE REVIEW

**Comment by oseasmoran73** [comment]
Test successful locally. Perhaps re-run job to verify?

**Comment by mikepenz** [comment]
Thank you so much for the PR. Will hopefully be able to review it over the weekend. 

The test failed due to:

```
  ● parseFile › should parse disabled tests

    thrown: "Exceeded timeout of 10000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."
```

maybe we need to expand the timeout, not sure though why it would need more than 10 secs to parse the file now

**Comment by oseasmoran73** [comment]
Hi @mikepenz ,

Thanks for reaching out and letting me know. Very much appreciate it :) and do give feedback/let me know if anything else is needed on my end.

Very strange. My hunch is this is a one-off instance.

**Comment by mikepenz** [comment]
Thank you so much for the PR :)

**Pull request merged**
