### PR TITLE
Adds prefix path to paths in junit report

### PR DESCRIPTION
**Pull request by kjeldahl**
In a monorepo setup the paths in the junit reports are relative to a subfolder in the repository and the annotations using the paths from the junit reports are not visible in github as the paths mismatch.

I could not find a way to configure the action-junit-report so I added this `test_files_prefix` that will be prepended to the path found in the junit reports when creating the github annotations so that the paths will match the paths in the repository.

### CODE REVIEW

**Comment by mikepenz** [comment]
Thank you for the PR. 

In your environment I assume the paths in the test report are relative already? 

The action already has an inverse approach were absolute paths are made relative, and that would also work for mono repos if the reports have absolute paths?

Mainly asking to get full understanding of the environment. Only adding the subpath before if provided may also result in failures if there is a mix between relative and absolute for example

**Comment by kjeldahl** [comment]
Yes, the paths are relative to the subfolder in the main repo.

```
root
      |-> projekt1
      |   |-> lib/code.rb
      |   |-> reports
      |      |-> junit_proj1_test_result.xml
      |-> projekt2
          |-> lib/stuff.rb
          |-> reports
             |-> junit_proj2_test_result.xml
```
junit_proj1_test_result.xml has filepaths like `lib/code.rb` and junit_proj2_test_result.xml has paths like `lib/stuff.rb`
I use https://github.com/minitest-reporters/minitest-reporters to generate the files.

**Comment by mikepenz** [comment]
Thank you for the additional input.

**Comment by kjeldahl** [comment]
@mikepenz I have found a way to add the prefix to the file paths in the junit xml files. So if you do not think this feature is appropriate for this project you can just close this pull request.

The Minitest::JUnitReporter has a base_path that can be used to add a prefix

**Comment by mikepenz** [comment]
Thank you very much @kjeldahl for adding the update here. 

I'd like to keep it open for now, to see if other people would potentially chime in, needing something similar.

**Comment by sayhiben** [comment]
I would like to see this feature added. I am using Django with [this library that does not allow me to force a git-root relative prefix](https://github.com/xmlrunner/unittest-xml-reporting) for `testsuite` or `testcase` `file` attributes.

To work around this, I had to write a short script to post-process my xml file so that the test failure annotations would show up in my pull requests:

.github/workflows/scripts/prefix_paths.py
```python
#!/usr/bin/env python3
import sys
import xml.etree.ElementTree as ET


def prefix_paths(xml_filepath, prefix):
    tree = ET.parse(xml_filepath)
    root = tree.getroot()
    testsuites = root.findall('testsuite')
    for testsuite in testsuites:
        testsuite.set('file', f"{prefix}{testsuite.get('file')}")
        testcases = testsuite.findall('testcase')
        for testcase in testcases:
            testcase.set('file', f"{prefix}{testcase.get('file')}")
    tree.write(xml_filepath)


if __name__ == '__main__':
    xml_filepath = sys.argv[1]
    prefix = sys.argv[2]
    prefix_paths(xml_filepath, prefix)
```

.github/workflows/main.yml:
```yaml
...

  - name: Run tests
    run: python ./my_app/src/manage.py test

  - name: Replace relative paths in unit test results output
    if: always()
    run: |
      python ./.github/workflows/scripts/prefix_paths.py results.xml my_app/src/

  - name: Publish Test Results
    if: always()
    uses: mikepenz/action-junit-report@v3
    with:
      report_paths: "results.xml"

...
```

Without this post-processing step, the `<testsuite>` and `<testcase>` elements use a relative path for their `file` attributes that does not match any paths that GitHub recognizes, e.g., `<testcase file="tests/mytestsuite.py" ...>` instead of `<testcase file="my_app/src/tests/mytestsuite.py" ...>`. This means my failure annotations don't show up in my PRs.

**Review by sayhiben — COMMENTED** [review]
The core change in this PR seems sensible. I would like to see an update to README.md included that describes the new options. 

Edit: The rest of this PR looks good, too. I'd like to see these changes before this merges:
- Update README.md to describe the new input
- Fix merge conflicts

Nice work on this PR!

**Comment by kjeldahl** [comment]
@sayhiben thank you very much. First time I have ever written any typescript. Very impressed with how easy it was get started working on this project 👍

**Comment by mikepenz** [comment]
@kjeldahl really appreciate your contribution!

**Pull request merged**
